#!/bin/bash

log() { echo >&2 "[start-postgres] $*"; }

log "Starting postgres..."
docker run -d \
    --name slonik-test-postgres \
    --publish 5432:5432 \
    --env POSTGRES_PASSWORD=odktest \
    --env POSTGRES_HOST_AUTH_METHOD=trust \
    --mount type=tmpfs,destination=/var/lib/postgresql/data,tmpfs-size=1g \
    --mount type=tmpfs,destination=/tmp \
    --mount type=tmpfs,destination=/run \
    --log-driver none \
    --read-only \
    --health-cmd pg_isready \
    --health-interval 1s \
    --health-timeout 5s \
    --health-retries 50 \
    postgres:14 \
        -c fsync=off \
        -c synchronous_commit=off \
        -c full_page_writes=off
log "Postgres started OK."
